version: 2

sources:
  - name: pto
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: pto
    loader: Airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 7, period: day}
      error_after: {count: 8, period: day}

    tables:
    - name: gitlab_pto
