version: 2

sources:
  - name: zuora_central_sandbox
    tags: ["tdf","zuora_central_sandbox"]
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: zuora_central_sandbox_fivetran
    loader: fivetran
    loaded_at_field: _FIVETRAN_SYNCED

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: account
        columns:
          - name: id
            description: Primary Key for Accounts
            tests:
              - dbt_utils.expression_is_true:
                  expression: "id REGEXP '[0-9a-z]{32}'"
      - name: accounting_period
      - name: amendment
      - name: contact
      - name: invoice
      - name: invoice_item
      - name: invoice_payment
      - name: product
      - name: product_rate_plan
      - name: product_rate_plan_charge
      - name: product_rate_plan_charge_tier
      - name: rate_plan
      - name: rate_plan_charge
      - name: rate_plan_charge_tier
      - name: refund
      - name: revenue_schedule_item
      - name: subscription
