version: 2

sources:
  - name: keyhole_twitter
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: keyhole_twitter
    loader: Stitch
    loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: impressions
        description: '{{ doc("twitter_impressions") }}'
