version: 2

models:
  - name: gitlab_dotcom_groups
    description: '{{ doc("gitlab_dotcom_groups") }}'
    columns:
      - name: group_id
        tests:
          - not_null
          - unique
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null

  - name: gitlab_dotcom_namespace_historical_daily
    columns:
      - name: snapshot_day_namespace_id
        tags: ["tdf","gitlab_dotcom"]
        tests:
          - not_null
          - unique
  
  - name: gitlab_dotcom_namespace_historical_monthly
    columns:
      - name: CONCAT(snapshot_month, namespace_id)
        tags: ["tdf","gitlab_dotcom"]
        tests:
          - unique

  - name: gitlab_dotcom_namespace_lineage
    description: '{{ doc("gitlab_dotcom_namespace_lineage") }}'
    columns:
      - name: namespace_id
        tests:
          - not_null
          - unique
      - name: parent_id
        description: >-
          The direct parent of a namespace. Will only be null for top-level
          namespaces.
      - name: upstream_lineage
        description: >-
          An array of the namespace's parent (upstream) lineage. Direction from
          left to right is young to old [namespace, parent, grandparent, ...]
        tests:
          - not_null
      - name: ultimate_parent_id
        description: >-
          The last (furthest right) item in upstream_lineage. I.E. the parent
          which has no parent. For top-level namespaces, this is will be
          itself.
        tests:
          - not_null
      - name: namespace_is_internal
        description: >-
          Whether or not the *ultimate parent* is a namespace that is internal to GitLab Inc.
        tests:
          - not_null
      - name: namespace_plan_id
        tests:
          - not_null
      - name: ultimate_parent_plan_id
        description: >-
          The plan_id of the namespace's ultimate parent namespace. This is inheritted downwards,
          meaning a namespace's ultimate_parent_plan_id will supersede its own plan_id whenever its plan
          is higher (ex: a Silver ultimate parent plan will override a namespace's Bronze plan.)
        tests:
          - not_null
          
  - name: gitlab_dotcom_namespace_lineage_prep
    description: '{{ doc("gitlab_dotcom_namespace_lineage") }}'
    columns:
      - name: namespace_id
        tests:
          - not_null
          - unique
      - name: parent_id
        description: >-
          The direct parent of a namespace. Will only be null for top-level
          namespaces.
      - name: upstream_lineage
        description: >-
          An array of the namespace's parent (upstream) lineage. Direction from
          left to right is young to old [namespace, parent, grandparent, ...]
        tests:
          - not_null
      - name: ultimate_parent_id
        description: >-
          The last (furthest right) item in upstream_lineage. I.E. the parent
          which has no parent. For top-level namespaces, this is will be
          itself.
        tests:
          - not_null
      - name: namespace_plan_id
        tests:
          - not_null
      - name: ultimate_parent_plan_id
        description: >-
          The plan_id of the namespace's ultimate parent namespace. This is inheritted downwards,
          meaning a namespace's ultimate_parent_plan_id will supersede its own plan_id whenever its plan
          is higher (ex: a Silver ultimate parent plan will override a namespace's Bronze plan.)
        tests:
          - not_null
  
  - name: gitlab_dotcom_namespace_lineage_historical_daily
    columns:
      - name: snapshot_day_namespace_id
        tags: ["tdf","gitlab_dotcom"]
        tests:
          - not_null
          - unique
  
  - name: gitlab_dotcom_namespace_lineage_historical_monthly
    columns:
      - name: CONCAT(snapshot_month, namespace_id)
        tags: ["tdf","gitlab_dotcom"]
        tests:
          - unique

  - name: gitlab_dotcom_namespace_statistics_historical_monthly

  - name: gitlab_dotcom_namespace_storage_statistics_historical_monthly




          
