version: 2

models:
  - name: gcp_billing_export
    description: Base model for gcp billing export
    columns:
      - name: billing_account_id
        tests:
          - not_null

  - name: gcp_billing_export_credits
    description: table for unnested credit rows
    columns:
      - name: credits_pk
        tests:
          - not_null
          - unique
      - name: source_primary_key
        tests:
          - not_null

  - name: gcp_billing_export_labels
    description: table for unnested label rows
    columns:
      - name: labels_pk
        tests:
          - not_null
          - unique
      - name: source_primary_key
        tests:
          - not_null
