{%- macro product_category(product_column, output_column_name = 'product_category') -%}

CASE
  WHEN zuora_product_rate_plan.effective_start_date >= '2021-01-01'
    AND LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%saas%'
    AND LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%ultimate%'
    THEN 'SaaS - Ultimate'
  WHEN zuora_product_rate_plan.effective_start_date >= '2021-01-01'
    AND LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%saas%'
    AND LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%premium%'
    THEN 'SaaS - Premium'
  WHEN zuora_product_rate_plan.effective_start_date >= '2021-01-01'
    AND LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%self-managed%'
    AND LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%ultimate%'
    THEN 'Self-Managed - Ultimate'
  WHEN zuora_product_rate_plan.effective_start_date >= '2021-01-01'
    AND LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%self-managed%'
    AND LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%premium%'
    THEN 'Self-Managed - Premium'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'gold%'
    THEN 'SaaS - Gold'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'silver%'
    THEN 'SaaS - Silver'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'bronze%'
    THEN 'SaaS - Bronze'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%starter%'
    THEN 'Self-Managed - Starter'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'gitlab enterprise edition%'
    THEN 'Self-Managed - Starter'
  WHEN zuora_product_rate_plan.product_rate_plan_name = 'Pivotal Cloud Foundry Tile for GitLab EE'
    THEN 'Self-Managed - Starter'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'plus%'
    THEN 'Plus'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'standard%'
    THEN 'Standard'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'basic%'
    THEN 'Basic'
  WHEN zuora_product_rate_plan.product_rate_plan_name = 'Trueup'
    THEN 'Trueup'
  WHEN LTRIM(LOWER(zuora_product_rate_plan.product_rate_plan_name)) LIKE 'githost%'
    THEN 'GitHost'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE '%quick start with ha%'
    THEN 'Support'
  WHEN TRIM(zuora_product_rate_plan.product_rate_plan_name) IN (
                                                                'GitLab Service Package'
                                                                , 'Implementation Services Quick Start'
                                                                , 'Implementation Support'
                                                                , 'Support Package'
                                                                , 'Admin Training'
                                                                , 'CI/CD Training'
                                                                , 'GitLab Project Management Training'
                                                                , 'GitLab with Git Basics Training'
                                                                , 'Travel Expenses'
                                                                , 'Training Workshop'
                                                                , 'GitLab for Project Managers Training - Remote'
                                                                , 'GitLab with Git Basics Training - Remote'
                                                                , 'GitLab for System Administrators Training - Remote'
                                                                , 'GitLab CI/CD Training - Remote'
                                                                , 'InnerSourcing Training - Remote for your team'
                                                                , 'GitLab DevOps Fundamentals Training'
                                                                , 'Self-Managed Rapid Results Consulting'
                                                               )
    THEN 'Support'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'gitlab geo%'
    THEN 'Other'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'ci runner%'
    THEN 'Other'
  WHEN LOWER(zuora_product_rate_plan.product_rate_plan_name) LIKE 'discount%'
    THEN 'Other'
  WHEN TRIM(zuora_product_rate_plan.product_rate_plan_name) IN (
                                                                '#movingtogitlab'
                                                                , 'File Locking'
                                                                , 'Payment Gateway Test'
                                                                , 'Time Tracking'
                                                                , '1,000 CI Minutes'
                                                                , 'Gitlab Storage 10GB'
                                                               )
    THEN 'Other'
  ELSE 'Not Applicable'
END AS {{output_column_name}}

{%- endmacro -%}