version: 2

models:
  - name: gitlab_dotcom_alert_management_alert_assignees_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_alert_management_alerts_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_alerts_service_data_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_application_settings_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_approval_merge_request_rules_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_approvals_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_approver_groups_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_audit_events_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_board_assignees_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_board_labels_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_boards_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_build_trace_chunks_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_build_trace_section_names_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_builds_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_group_variables_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_job_artifacts_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_pipeline_chat_data_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_pipeline_schedule_variables_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_pipeline_schedules_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_pipeline_variables_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_pipelines_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_platform_metrics_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_runner_projects_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_runners_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_stages_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_trigger_requests_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_ci_triggers_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_cluster_groups_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_cluster_projects_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_applications_cert_managers_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_applications_crossplane_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_applications_elastic_stacks_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_applications_helm_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_applications_ingress_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_applications_jupyter_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_applications_knative_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_applications_prometheus_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_applications_runners_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_clusters_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_deployment_merge_requests_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_deployments_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_design_management_designs_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_design_management_designs_versions_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_design_management_versions_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_elasticsearch_indexed_namespaces_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_emails_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_environments_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_epic_issues_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_epic_metrics_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_epics_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_events_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_experiment_users_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_experiments_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_gitlab_subscription_histories_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_identities_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_issue_assignees_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_issue_metrics_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_issues_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_keys_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_label_priorities_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_labels_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_lfs_objects_projects_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_licenses_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_lists_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_merge_request_diffs_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_merge_request_metrics_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_merge_requests_closing_issues_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_merge_requests_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_milestones_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_namespace_root_storage_statistics_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_namespace_statistics_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_namespaces_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_notes_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_notification_settings_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_oauth_access_tokens_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_packages_packages_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_pages_domains_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_plans_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_programming_languages_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_project_authorizations_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_project_auto_devops_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_project_features_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_project_import_data_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_project_mirror_data_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_project_repositories_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_project_repository_storage_moves_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_project_statistics_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_projects_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_prometheus_alerts_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_protected_branches_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_push_rules_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_releases_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_repository_languages_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_requirements_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_resource_label_events_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_resource_milestone_events_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_resource_weight_events_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_saml_providers_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_services_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_shards_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_snippets_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_sprints_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_subscriptions_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_system_note_metadata_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_terraform_states_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_timelogs_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_todos_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_user_preferences_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_users_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_vulnerabilities_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
  - name: gitlab_dotcom_vulnerability_occurrences_dedupe_source
    description: '{{ doc("gitlab_dotcom_gitlab_emails_cleaned") }}'
