version: 2

models:
    - name: accepted_solutions
      description: '{{ doc("accepted_solutions") }}'
      columns:
          - name: report_start_date
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: consolidated_page_views
      description: '{{ doc("consolidated_page_views") }}'
      columns:
          - name: report_start_date
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: request_type
          - name: request_label
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: daily_engaged_users
      description: '{{ doc("daily_engaged_users") }}'
      columns:
          - name: report_start_date
            tests:
              - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: page_view_total_reqs
      description: '{{ doc("page_view_total_reqs") }}'
      columns:
          - name: report_start_date
            tests:
            - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
            - not_null
          - name: report_value
            tests:
            - not_null

    - name: posts
      description: '{{ doc("posts") }}'
      columns:
          - name: report_start_date
            tests:
              - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
              - not_null
          - name: report_value
            tests:
              - not_null

    - name: signups
      description: '{{ doc("signups") }}'
      columns:
          - name: report_start_date
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: time_to_first_response
      description: '{{ doc("time_to_first_response") }}'
      columns:
          - name: report_start_date
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: topics_with_no_response
      description: '{{ doc("topics_with_no_response") }}'
      columns:
          - name: report_start_date
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null

    - name: visits
      description: '{{ doc("visits") }}'
      columns:
          - name: report_start_date
            tests:
                - not_null
          - name: report_title
          - name: report_type
          - name: report_value_date
            tests:
                - not_null
          - name: report_value
            tests:
                - not_null







