version: 2

models:
- name: rpt_event_xmau_metric_monthly
  description: '{{ doc("rpt_event_xmau_metric_monthly") }}'
  columns:
    - name: xmau_metric_monthly_id
      description: the unique ID of a monthly xMAU metric in rpt_xmau_metric_monthly
      tests:
        - not_null
        - unique
    - name: event_calendar_month
      description: '{{ doc("event_calendar_month") }}'
    - name: is_smau
      description: '{{ doc("is_smau") }}'
    - name: is_gmau
      description: '{{ doc("is_gmau") }}'
    - name: is_umau
      description: '{{ doc("is_umau") }}'
    - name: stage_name
      description: '{{ doc("stage_name") }}'
    - name: section_name
      description: '{{ doc("section_name") }}'
    - name: group_name
      description: '{{ doc("group_name") }}'
    - name: user_group
      description: '{{ doc("user_group") }}'
    - name: event_name_array
      description: '{{ doc("event_name_array") }}'
    - name: event_count
      description: '{{ doc("event_count") }}'
    - name: ultimate_parent_namespace_count
      description: '{{ doc("ultimate_parent_namespace_count") }}'
    - name: user_count
      description: '{{ doc("user_count") }}'
    - name: created_by
      description: '{{ doc("created_by") }}'
    - name: updated_by
      description: '{{ doc("updated_by") }}'
    - name: model_created_date
      description: '{{ doc("model_created_date") }}'
    - name: model_updated_date
      description: '{{ doc("model_updated_date") }}'

- name: rpt_event_plan_monthly
  description: '{{ doc("rpt_event_plan_monthly") }}'
  columns:
    - name: event_plan_monthly_id
      description: the unique ID of a montthly usage event plan in rpt_usage_event_plan_monthly
      tests:
        - not_null
        - unique
    - name: event_calendar_month
      description: '{{ doc("event_calendar_month") }}'
    - name: event_calendar_quarter
      description: '{{ doc("event_calendar_quarter") }}'
    - name: event_calendar_year
      description: '{{ doc("event_calendar_year") }}'
    - name: plan_id_at_event_date
      description: '{{ doc("plan_id_at_event_date") }}'
    - name: event_name
      description: '{{ doc("event_name") }}'
    - name: is_smau
      description: '{{ doc("is_smau") }}'
    - name: is_gmau
      description: '{{ doc("is_gmau") }}'
    - name: is_umau
      description: '{{ doc("is_umau") }}'
    - name: stage_name
      description: '{{ doc("stage_name") }}'
    - name: section_name
      description: '{{ doc("section_name") }}'
    - name: group_name
      description: '{{ doc("group_name") }}'
    - name: event_count
      description: '{{ doc("event_count") }}'
    - name: ultimate_parent_namespace_count
      description: '{{ doc("ultimate_parent_namespace_count") }}'
    - name: user_count
      description: '{{ doc("user_count") }}'
    - name: created_by
      description: '{{ doc("created_by") }}'
    - name: updated_by
      description: '{{ doc("updated_by") }}'
    - name: model_created_date
      description: '{{ doc("model_created_date") }}'
    - name: model_updated_date
      description: '{{ doc("model_updated_date") }}'

- name: rpt_ping_metric_first_last_versions
  description: ' {{ doc("rpt_ping_metric_first_last_versions") }} '
  columns:
    - name: ping_metric_first_last_versions_id
      tests:
        - not_null
        - unique

- name: rpt_ping_latest_subscriptions_monthly
  description: ' {{ doc("rpt_ping_latest_subscriptions_monthly") }} '
  columns:
    - name: ping_latest_subscriptions_monthly_id
      tests:
        - not_null
        - unique

- name: rpt_ping_subscriptions_on_versions_estimate_factors_monthly
  description: ' {{ doc("rpt_ping_subscriptions_on_versions_estimate_factors_monthly") }} '
  columns:
    - name: ping_subscriptions_on_versions_estimate_factors_monthly_id
      tests:
        - not_null
        - unique
      description: the unique composite ID for the rpt_ping_instance_metric_adoption_monthly model consisting of reporting_month, metrics_path, and estimation_grain
    - name: ping_created_at_month
      description: The month when the ping was created
    - name: reporting_count
      description: The number of seats/subscriptions that reported on a version with the metric
    - name: not_reporting_count
      description: The number of seats/subscriptions that did not report on a version with the metric
    - name: total_count
      description: The total number of active seats/subscriptions that could have reported on a version with the metric
    - name: estimation_grain
      description: The estimation methodology being used, made up of a condition (ie. on a version with the metric) and a measure (ex. subscription count)
    - name: percent_reporting
      description: The percentage of seats/subscriptions on a version with the metric
    - name: stage_name
      description: The name of the product stage responsible for the metric
    - name: section_name
      description: The name of the product section responsible for the metric
    - name: group_name
      description: The name of the product group responsible for the metric
    - name: is_smau
      description: Boolean flag set to True if the metric is one of the counters chosen for the stage's SMAU calculation
    - name: is_gmau
      description: Boolean flag set to True if the metric is one of the counters chosen for the group's GMAU calculation
    - name: is_paid_gmau
      description: Boolean flag set to True if the metric is one of the counters chosen for the group's paid GMAU calculation
    - name: is_umau
      description: Boolean flag set to True if the metric is one of the counters chosen for UMAU calculation

- name: rpt_ping_metric_estimate_factors_monthly
  description: ' {{ doc("rpt_ping_metric_estimate_factors_monthly") }} '
  columns:
    - name: ping_metric_estimate_factors_monthly_id
      tests:
        - not_null
        - unique

- name: rpt_ping_subscriptions_reported_estimate_factors_monthly
  description: ' {{ doc("rpt_ping_subscriptions_reported_estimate_factors_monthly") }} '
  columns:
    - name: ping_subscriptions_reported_estimate_factors_monthly_id
      tests:
        - not_null
        - unique

- name: rpt_ping_metric_totals_w_estimates_monthly
  description: ' {{ doc("rpt_ping_metric_totals_w_estimates_monthly") }} '
  columns:
    - name: ping_metric_totals_w_estimates_monthly_id
      tests:
        - not_null
        - unique
      description: the unique composite ID for the rpt_ping_metric_totals_w_estimates_monthly model consisting of reporting_month, metrics_path, estimation_grain, ping_edition_product_tier, and service_ping_delivery_type
    - name: metrics_path
      description: The unique JSON key path of identifier of the metric in the ping payload. This appears as key_path in the metric definition YAML files
    - name: ping_created_at_month
      description: The month when the ping was created
    - name: ping_delivery_type
      description: How the product is delivered to the installation (Self-Managed, SaaS)
    - name: ping_edition
      description: The edition of GitLab on the installation (EE, CE)
    - name: ping_product_tier
      description: The product tier of the ping, inferred from the edition and the plan saved in the license (Core, Starter Premium, Ultimate)
    - name: ping_edition_product_tier
      description: A combination of the ping_edition and the ping_product_tier (EE - Self-Managed - Free, EE - Self-Managed - Premium, EE - Self-Managed - Ultimate)
    - name: stage_name
      description: The name of the product stage responsible for the metric
    - name: section_name
      description: The name of the product section responsible for the metric
    - name: group_name
      description: The name of the product group responsible for the metric
    - name: is_smau
      description: Boolean flag set to True if the metric is one of the counters chosen for the stage's SMAU calculation
    - name: is_gmau
      description: Boolean flag set to True if the metric is one of the counters chosen for the group's GMAU calculation
    - name: is_paid_gmau
      description: Boolean flag set to True if the metric is one of the counters chosen for the group's paid GMAU calculation
    - name: is_umau
      description: Boolean flag set to True if the metric is one of the counters chosen for UMAU calculation
    - name: reporting_count
      description: The number of seats/subscriptions that met the condition (ex. reported the metric)
    - name: not_reporting_count
      description: The number of seats/subscriptions that did not meet the condition (ex. report the metric)
    - name: percent_reporting
      description: The percentage of the measure (subscriptions or seats) meeting the condition (ex. reporting the metric)
    - name: estimation_grain
      description: The estimation methodology being used, made up of a condition (ex. reporting a metric) and a measure (ex. subscription count)
    - name: total_usage_with_estimate
      description: Total usage, including the estimate
    - name: estimated_usage
      description: Estimated usage based on recorded data and estimation grain/methodology
    - name: recorded_usage
      description: Actual recorded usage
    - name: created_by
      description: The GitLab handle of the original model creator
    - name: updated_by
      description: The GitLab handle of the most recent model editor
    - name: model_created_date
      description: Manually input ISO date of when model was original created
    - name: model_updated_date
      description: Manually input ISO date of when model was updated
    - name: dbt_updated_at
    - name: dbt_created_at


- name: rpt_ping_subscriptions_reported_counts_monthly
  description: ' {{ doc("rpt_ping_subscriptions_reported_counts_monthly") }} '
  columns:
    - name: ping_subscriptions_reported_counts_monthly_id
      tests:
        - not_null
        - unique

- name: rpt_ping_subscriptions_on_versions_counts_monthly
  description: ' {{ doc("rpt_ping_subscriptions_on_versions_counts_monthly") }} '
  columns:
    - name: ping_subscriptions_on_versions_counts_monthly_id
      tests:
        - not_null
        - unique
