version: 2

sources:
  - name: version
    tags: ["tdf","version"]
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: version_db_dump_stitch
    loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: avg_cycle_analytics
        columns:
          - name: id
            tags:
              - tdf
              - version
            tests:
              - not_null
      - name: conversational_development_indices
        columns:
          - name: id
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: created_at
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: updated_at
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: usage_data_id
            tags:
              - tdf
              - version
            tests:
              - not_null    
      - name: current_host_stats
        columns:
          - name: id
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: created_at
            tags:
              - tdf
              - version
            tests:
              - not_null 
          - name: updated_at
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: host_id
            tags:
              - tdf
              - version
            tests:
              - not_null             
      - name: fortune_companies
      - name: hosts
        columns:
          - name: id
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: created_at
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: updated_at
            tags:
              - tdf
              - version
            tests:
              - not_null
      - name: raw_usage_data
        columns:
          - name: id
            tags:
              - tdf
              - version
            tests:
              - not_null
              - unique
      - name: schema_migrations
      - name: usage_data
        columns:
          - name: id
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: created_at
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: updated_at
            tags:
              - tdf
              - version
            tests:
              - not_null
      - name: version_checks
        columns:
          - name: id
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: created_at
            tags: 
              - tdf
              - version
            tests:
              - not_null
          - name: updated_at
            tags:
              - tdf
              - version
            tests:
              - not_null
      - name: versions
        columns:
          - name: id
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: created_at
            tags:
              - tdf
              - version
            tests:
              - not_null
          - name: updated_at
            tags:
              - tdf
              - version
            tests:
              - not_null
      - name: users              
