version: 2

models:
  - name: zuora_revenue_accounting_type_source
    description: Accounting type for all accounts used in Zuora Revenue.
    columns:
      - name: accounting_type_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_approval_detail_source
    description: Record of approvals required for revenue contracts.
    columns:
      - name: revenue_contract_approval_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_book_source
    description: Accounting books used in Zuora Revenue
    columns:
      - name: book_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_calendar_source
    description: Calendars used for recognizing revenue in Zuora Revenue.
    columns:
      - name: calendar_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_manual_journal_entry_source
    description: Manual journal entry adjustments to revenue contracts.
    columns: 
      - name: manual_journal_entry_line_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_organization_source
    description: The organizations who have revenue to be recognized in Zuora Revenue.
    columns:
      - name: organization_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_revenue_contract_bill_source
    description: Customer bills generated from revenue contracts.
    columns:
      - name: invoice_item_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_header_source
    description: Revenue contract details rolled up from the lines.
    columns:
      - name: revenue_contract_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_hold_source
    description: Record of holds placed on revenue contracts.
    columns:
      - name: revenue_contract_hold_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_line_source
    description: Line items from a revenue contract.
    columns:
      - name: revenue_contract_line_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_revenue_contract_performance_obligation_source
    description: Revenue contracts are split into invoiced items which are further divided into specific performance obligations which must be satisfied in order to recognize the revenue.
    columns:
      - name: revenue_contract_performance_obligation_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_revenue_contract_schedule_source
    description: Timeline for recognizing the revenue from revenue contract line items.
    columns:
      - name: schedule_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_revenue_contract_schedule_deleted
    description: Deleted scheduled previously used to understand when revenue from contracts would be recognized.
    columns:
      - name: schedule_id
        tags: ["tdf","zuora"]
        tests:
          - not_null
          - unique
  - name: zuora_revenue_account_summary_source
    description: Derived table from Zuora Revenue containing summarized account data.
  - name: zuora_revenue_waterfall_summary_source
    description: Displays snapshots of revenue contract line items by period showing how much has been recognized from each line item and what will be recognized in the future.