version: 2

models:
  - name: mart_monthly_product_usage
    description: '{{ doc("mart_monthly_product_usage") }}'
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
      - name: reporting_month
        description: '{{ doc("reporting_month") }}'
        tests:
            - not_null
      - name: metrics_path
        description: '{{ doc("metrics_path") }}'
        tests:
            - not_null
      - name: ping_id
        description: '{{ doc("ping_id") }}'
        tests:
            - not_null
      - name: host_id
        description: '{{ doc("host_id") }}'
      - name: license_id
        description: '{{ doc("license_id") }}'
      - name: host_id
        description: '{{ doc("license_md5") }}'
      - name: original_linked_subscription_id
        description: '{{ doc("original_linked_subscription_id") }}'
      - name: latest_active_subscription_id
        description: '{{ doc("latest_active_subscription_id") }}'
      - name: billing_account_id
        description: '{{ doc("billing_account_id") }}'
      - name: location_id
        description: '{{ doc("location_id") }}'
      - name: dim_parent_crm_account_id
        description: '{{ doc("dim_parent_crm_account_id") }}'
      - name: delivery
        description: '{{ doc("delivery_column") }}'
        tests:
            - not_null
      - name: main_edition
        description: '{{ doc("main_edition") }}'
        tests:
            - not_null
      - name: ping_product_tier
        description: '{{ doc("ping_product_tier") }}'
        tests:
            - not_null
      - name: ping_main_edition_product_tier
        description: '{{ doc("ping_main_edition_product_tier") }}'
        tests:
            - not_null
      - name: major_version
        description: '{{ doc("major_version") }}'
      - name: minor_version
        description: '{{ doc("minor_version") }}'
      - name: major_minor_version
        description: '{{ doc("major_minor_version") }}'
      - name: version
        description: '{{ doc("version") }}'
        tests:
            - not_null
      - name: source_ip_hash
        description: '{{ doc("source_ip_hash") }}'
      - name: is_pre_release
        description: '{{ doc("is_pre_release") }}'
      - name: is_internal
        description: '{{ doc("is_internal") }}'
      - name: is_staging
        description: '{{ doc("is_staging") }}'
      - name: is_trial
        description: '{{ doc("is_trial") }}'
      - name: group_name
        description: '{{ doc("group_name") }}'
      - name: stage_name
        description: '{{ doc("stage_name") }}'
      - name: section_name
        description: '{{ doc("section_name") }}'
      - name: is_smau
        description: '{{ doc("is_smau") }}'
      - name: is_gmau
        description: '{{ doc("is_gmau") }}'
      - name: is_paid_gmau
        description: '{{ doc("is_paid_gmau") }}'
      - name: is_umau
        description: '{{ doc("is_umau") }}'
      - name: host_name
        description: '{{ doc("host_name") }}'
      - name: subscription_name_slugify
        description: '{{ doc("subscription_name_slugify") }}'
      - name: subscription_start_month
        description: '{{ doc("subscription_start_month") }}'
      - name: subscription_end_month
        description: '{{ doc("subscription_end_month") }}'
      - name: product_category_array
        description: '{{ doc("product_category_array") }}'
      - name: product_rate_plan_name_array
        description: '{{ doc("product_rate_plan_name_array") }}'
      - name: is_paid_subscription
        description: '{{ doc("is_paid_subscription") }}'
      - name: is_program_subscription
        description: '{{ doc("is_edu_oss_subscription") }}'
      - name: crm_account_name
        description: '{{ doc("crm_account_name") }}'
      - name: parent_crm_account_name
        description: '{{ doc("parent_crm_account_name") }}'
      - name: parent_crm_account_billing_country
        description: '{{ doc("parent_crm_account_billing_country") }}'
      - name: parent_crm_account_sales_segment
        description: '{{ doc("parent_crm_account_sales_segment") }}'
      - name: parent_crm_account_industry
        description: '{{ doc("parent_crm_account_industry") }}'
      - name: parent_crm_account_owner_team
        description: '{{ doc("parent_crm_account_owner_team") }}'
      - name: parent_crm_account_sales_territory
        description: '{{ doc("parent_crm_account_sales_territory") }}'
      - name: technical_account_manager
        description: '{{ doc("technical_account_manager") }}'
      - name: created_at
        description: '{{ doc("created_at") }}'
      - name: recorded_at
        description: '{{ doc("recorded_at") }}'
        tests:
            - not_null
      - name: monthly_metric_value
        description: '{{ doc("monthly_metric_value") }}'
        tests:
            - not_null
      - name: created_by
        description: '{{ doc("created_by") }}'
        tests:
            - not_null
      - name: updated_by
        description: '{{ doc("updated_by") }}'
        tests:
            - not_null
      - name: model_created_date
        description: '{{ doc("model_created_date") }}'
        tests:
            - not_null
      - name: model_updated_date
        description: '{{ doc("model_updated_date") }}'
        tests:
            - not_null
      - name: dbt_updated_at
        description: '{{ doc("dbt_updated_at") }}'
        tests:
            - not_null
      - name: dbt_created_at
        description: '{{ doc("dbt_created_at") }}'
        tests:
            - not_null
  - name: mart_usage_ping_counters_statistics
    description: '{{ doc("mart_usage_ping_counters_statistics") }}'
    tests:
      - unique:
          column_name: "concat(metrics_path, edition)"
    columns:
      - name: metrics_path
        tests:
            - not_null
  - name: mart_paid_subscriptions_monthly_usage_ping_optin
    description: '{{ doc("mart_paid_subscriptions_monthly_usage_ping_optin") }}'
    columns:
      - name: month_subscription_id
        tests:
            - not_null
            - unique
      - name: arr
        description: "Calculated as 12 * MRR value"
      - name: subscription_name_slugify
        description: Unique key of a subscription
      - name: has_sent_payloads
        description: boolean flag to identify if for a specific month reporting_month and a specific subscription_name_slugify, a usage ping payload has been received.
      - name: latest_major_minor_version
        description: for a specific month reporting_month and a specific subscription_name_slugify, the latest version of the GitLab Application used.
