version: 2

models:
  - name: prep_sfdc_account
    description: '{{ doc("prep_sfdc_account") }}'
    columns:
      - name: crm_account_id
        description: CRM Account ID provided by Salesforce
        tests:
          - not_null
      - name: tsp_sub_region_clean
        description: Sales sub region, temp cleaning column
      - name: tsp_region_clean
        description: Sales region, temp cleaning column
      - name: tsp_area_clean
        description: Sales area, temp cleaning column
      - name: tsp_territory_clean
        description: Sales territory, temp cleaning column
      - name: df_industry_clean
        description: Industry, temp cleaning column
      - name: ultimate_parent_sales_segment_clean
        description: Ultimate parent sales segment, temp cleaning column
      - name: dim_geo_area_name_source
        description: Dim geo area name final source column
      - name: dim_geo_region_name_source
        description: Dim geo region name final source column
      - name: dim_geo_sub_region_name_source
        description: Dim geo sub region name final source column
      - name: dim_sales_territory_name_source
        description: Dim sales territory name final source column
      - name: dim_industry_name_source
        description: Dim industry name final source column
      - name: dim_sales_segment_name_source
        description: Dim sales segment name final source column

  - name: prep_sales_hierarchy
    description: '{{ doc("prep_sales_hierarchy") }}'
    columns:
      - name: dim_sales_hierarchy_id
        description: Unique identifier of sales hierarchy based on user segment, geo, region, and area
        tests:
          - not_null
          - unique 
