CREATE TABLE IF NOT EXISTS BI3_WF_SUMM ( 
ACCTG_SEG  VARCHAR,
ACCTG_TYPE_ID  VARCHAR,
AS_OF_PRD_ID  VARCHAR,
BOOK_ID  VARCHAR,
CLIENT_ID  VARCHAR,
CRTD_BY  VARCHAR,
CRTD_DT  VARCHAR,
CRTD_PRD_ID  VARCHAR,
F_AT  VARCHAR,
INCR_UPDT_DT  VARCHAR,
LINE_ID  VARCHAR,
NETTING_ENTRY_FLAG  VARCHAR,
POST_PRD_ID  VARCHAR,
PRD_ID  VARCHAR,
ROOT_LINE_ID  VARCHAR,
R_AT  VARCHAR,
SCHD_ID  VARCHAR,
SCHD_TYPE_FLAG  VARCHAR,
SEC_ATR_VAL  VARCHAR,
T_AT  VARCHAR,
UPDT_BY  VARCHAR,
UPDT_DT  VARCHAR
)
;
 
 
 
 
 /* Original Table definition for reference or Downstream modification. 
 CREATE TABLE IF NOT EXISTS BI3_WF_SUMM ( 
ACCTG_SEG  VARCHAR2,
ACCTG_TYPE_ID  VARCHAR2,
AS_OF_PRD_ID  NUMBER,
BOOK_ID  NUMBER,
CLIENT_ID  NUMBER,
CRTD_BY  VARCHAR2,
CRTD_DT  DATE,
CRTD_PRD_ID  NUMBER,
F_AT  NUMBER,
INCR_UPDT_DT  DATE,
LINE_ID  NUMBER,
NETTING_ENTRY_FLAG  VARCHAR2,
POST_PRD_ID  NUMBER,
PRD_ID  NUMBER,
ROOT_LINE_ID  NUMBER,
R_AT  NUMBER,
SCHD_ID  NUMBER,
SCHD_TYPE_FLAG  VARCHAR2,
SEC_ATR_VAL  VARCHAR2,
T_AT  NUMBER,
UPDT_BY  VARCHAR2,
UPDT_DT  DATE
);
*/