CREATE TABLE IF NOT EXISTS BI3_BOOK ( 
ALLOCATION_FLAG  VARCHAR,
ASST_SEGMENTS  VARCHAR,
BNDL_EXPL_FLAG  VARCHAR,
CLIENT_ID  VARCHAR,
CRTD_BY  VARCHAR,
CRTD_DT  VARCHAR,
CRTD_PRD_ID  VARCHAR,
DESCRIPTION  VARCHAR,
ENABLED_FLAG  VARCHAR,
END_DATE  VARCHAR,
HARD_FREEZE_FLAG  VARCHAR,
ID  VARCHAR,
INCR_UPDT_DT  VARCHAR,
LBLTY_SEGMENTS  VARCHAR,
LTST_ENABLED_FLAG  VARCHAR,
NAME  VARCHAR,
OPEN_PRD_ID  VARCHAR,
POSTABLE_FLAG  VARCHAR,
PRIMARY_BOOK_FLAG  VARCHAR,
RC_PREFIX  VARCHAR,
SOFT_FREEZE_FLAG  VARCHAR,
START_DATE  VARCHAR,
TYPE  VARCHAR,
UPDT_BY  VARCHAR,
UPDT_DT  VARCHAR
)
;
 
 
 
 
 /* Original Table definition for reference or Downstream modification. 
 CREATE TABLE IF NOT EXISTS BI3_BOOK ( 
ALLOCATION_FLAG  VARCHAR2,
ASST_SEGMENTS  VARCHAR2,
BNDL_EXPL_FLAG  VARCHAR2,
CLIENT_ID  NUMBER,
CRTD_BY  VARCHAR2,
CRTD_DT  DATE,
CRTD_PRD_ID  NUMBER,
DESCRIPTION  VARCHAR2,
ENABLED_FLAG  VARCHAR2,
END_DATE  DATE,
HARD_FREEZE_FLAG  VARCHAR2,
ID  NUMBER,
INCR_UPDT_DT  DATE,
LBLTY_SEGMENTS  VARCHAR2,
LTST_ENABLED_FLAG  VARCHAR2,
NAME  VARCHAR2,
OPEN_PRD_ID  NUMBER,
POSTABLE_FLAG  VARCHAR2,
PRIMARY_BOOK_FLAG  VARCHAR2,
RC_PREFIX  VARCHAR2,
SOFT_FREEZE_FLAG  VARCHAR2,
START_DATE  DATE,
TYPE  VARCHAR2,
UPDT_BY  VARCHAR2,
UPDT_DT  DATE
);
*/