CREATE TABLE IF NOT EXISTS BI3_RC_SCHD_DEL ( 
CLIENT_ID  VARCHAR,
CRTD_BY  VARCHAR,
CRTD_DT  VARCHAR,
DELETED_TIME  VARCHAR,
INCR_UPDT_DT  VARCHAR,
SCHD_ID  VARCHAR,
UPDT_BY  VARCHAR,
UPDT_DT  VARCHAR
)
;
 
 
 
 
 /* Original Table definition for reference or Downstream modification. 
 CREATE TABLE IF NOT EXISTS BI3_RC_SCHD_DEL ( 
CLIENT_ID  NUMBER,
CRTD_BY  VARCHAR2,
CRTD_DT  DATE,
DELETED_TIME  DATE,
INCR_UPDT_DT  DATE,
SCHD_ID  NUMBER,
UPDT_BY  VARCHAR2,
UPDT_DT  DATE
);
*/