CREATE TABLE IF NOT EXISTS BI3_CALENDAR ( 
CLIENT_ID  VARCHAR,
CRTD_BY  VARCHAR,
CRTD_DT  VARCHAR,
END_DATE  VARCHAR,
ID  VARCHAR,
INCR_UPDT_DT  VARCHAR,
PERIOD_NAME  VARCHAR,
PERIOD_NUM  VARCHAR,
PERIOD_YEAR  VARCHAR,
QTR_END_DT  VARCHAR,
QTR_NUM  VARCHAR,
QTR_START_DT  VARCHAR,
START_DATE  VARCHAR,
UPDT_BY  VARCHAR,
UPDT_DT  VARCHAR,
YEAR_END_DT  VARCHAR,
YEAR_START_DT  VARCHAR
)
;
 
 
 
 
 /* Original Table definition for reference or Downstream modification. 
 CREATE TABLE IF NOT EXISTS BI3_CALENDAR ( 
CLIENT_ID  NUMBER,
CRTD_BY  VARCHAR2,
CRTD_DT  DATE,
END_DATE  DATE,
ID  NUMBER,
INCR_UPDT_DT  DATE,
PERIOD_NAME  VARCHAR2,
PERIOD_NUM  NUMBER,
PERIOD_YEAR  NUMBER,
QTR_END_DT  DATE,
QTR_NUM  NUMBER,
QTR_START_DT  DATE,
START_DATE  DATE,
UPDT_BY  VARCHAR2,
UPDT_DT  DATE,
YEAR_END_DT  DATE,
YEAR_START_DT  DATE
);
*/