CREATE TABLE IF NOT EXISTS BI3_ORG ( 
CLIENT_ID  VARCHAR,
CRTD_BY  VARCHAR,
CRTD_DT  VARCHAR,
CRTD_PRD_ID  VARCHAR,
ENTITY_ID  VARCHAR,
ID  VARCHAR,
INCR_UPDT_DT  VARCHAR,
ORG_CODE  VARCHAR,
ORG_ID  VARCHAR,
ORG_NAME  VARCHAR,
UPDT_BY  VARCHAR,
UPDT_DT  VARCHAR
)
;
 
 
 
 
 /* Original Table definition for reference or Downstream modification. 
 CREATE TABLE IF NOT EXISTS BI3_ORG ( 
CLIENT_ID  NUMBER,
CRTD_BY  VARCHAR2,
CRTD_DT  DATE,
CRTD_PRD_ID  NUMBER,
ENTITY_ID  VARCHAR2,
ID  NUMBER,
INCR_UPDT_DT  DATE,
ORG_CODE  VARCHAR2,
ORG_ID  VARCHAR2,
ORG_NAME  VARCHAR2,
UPDT_BY  VARCHAR2,
UPDT_DT  DATE
);
*/