CREATE TABLE IF NOT EXISTS BI3_ACCT_TYPE ( 
ACCT_GROUP  VARCHAR,
ALLOW_MAPPING_FLAG  VARCHAR,
BALANCE_SHEET_ACCT_FLAG  VARCHAR,
CLIENT_ID  VARCHAR,
COST_FLAG  VARCHAR,
CRTD_BY  VARCHAR,
CRTD_DT  VARCHAR,
DEF_OFFSET_FLAG  VARCHAR,
DEF_REC_FLAG  VARCHAR,
ENABLED_FLAG  VARCHAR,
ID  VARCHAR,
INCL_IN_MANUAL_JE_FLAG  VARCHAR,
INCL_IN_NETTING_FLAG  VARCHAR,
INCR_UPDT_DT  VARCHAR,
NAME  VARCHAR,
PAYABLES_ACCT_FLAG  VARCHAR,
P_L_ACCT_FLAG  VARCHAR,
REVENUE_SUMMARY  VARCHAR,
REV_DISPLAY_SEQ  VARCHAR,
REV_OFFSET_FLAG  VARCHAR,
UPDT_BY  VARCHAR,
UPDT_DT  VARCHAR,
VC_ACCT_FLAG  VARCHAR,
VC_CLR_ACCT_FLAG  VARCHAR,
WATERFALL_FLAG  VARCHAR,
WF_SUMM_TYPE  VARCHAR,
WF_TYPE  VARCHAR
)
;
 
 
 
 
 /* Original Table definition for reference or Downstream modification. 
 CREATE TABLE IF NOT EXISTS BI3_ACCT_TYPE ( 
ACCT_GROUP  VARCHAR2,
ALLOW_MAPPING_FLAG  VARCHAR2,
BALANCE_SHEET_ACCT_FLAG  VARCHAR2,
CLIENT_ID  NUMBER,
COST_FLAG  VARCHAR2,
CRTD_BY  VARCHAR2,
CRTD_DT  DATE,
DEF_OFFSET_FLAG  VARCHAR2,
DEF_REC_FLAG  VARCHAR2,
ENABLED_FLAG  VARCHAR2,
ID  VARCHAR2,
INCL_IN_MANUAL_JE_FLAG  VARCHAR2,
INCL_IN_NETTING_FLAG  VARCHAR2,
INCR_UPDT_DT  DATE,
NAME  VARCHAR2,
PAYABLES_ACCT_FLAG  VARCHAR2,
P_L_ACCT_FLAG  VARCHAR2,
REVENUE_SUMMARY  VARCHAR2,
REV_DISPLAY_SEQ  NUMBER,
REV_OFFSET_FLAG  VARCHAR2,
UPDT_BY  VARCHAR2,
UPDT_DT  DATE,
VC_ACCT_FLAG  VARCHAR2,
VC_CLR_ACCT_FLAG  VARCHAR2,
WATERFALL_FLAG  VARCHAR2,
WF_SUMM_TYPE  VARCHAR2,
WF_TYPE  VARCHAR2
);
*/