version: 2

models:
  - name: subscription_product_usage_data
    description: '{{ doc("subscription_product_usage_data") }}'
    columns:
      - name: delivery_group
        tests: 
          - not_null
      - name: original_id
        tests: 
          - not_null
      - name: subscription_id
        tests:
          - not_null
          - unique
      - name: subscription_name
          - not_null

  - name: mart_product_usage_wave_1_3_metrics_latest
    description: '{{ doc("mart_product_usage_wave_1_3_metrics_latest") }}'
    columns:
      - name: dim_subscription_id
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: dim_subscription_id_original
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: dim_billing_account_id
        description: Returns unknown ID (MD5(-1)) if the `account_id` from `fct_product_usage_wave_1_3_metrics_monthly` is not found in `dim_billing_account`.
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: dim_crm_account_id
        description: Returns unknown ID (MD5(-1)) if the `dim_crm_account_id` from `dim_billing_account` is not found in `dim_crm_account`.
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: seat_link_report_date
        description: Day on which Seat Link usage data is reported. Should always be last day of month for historical months.
      - name: seat_link_report_date_id
      - name: license_utilization
        description: Number of activated seats (`active_user_count`) divided by the number of purchased seats (`license_user_count`) on the subscription.
      - name: active_user_count
        description: Count of active users currently on the customer's subcription. It is possible for a customer to opt out of sending this information to GitLab.
      - name: max_historical_user_count
        description: Maximum active user count ever reported over the lifetime of the customer's subcription.
      - name: license_user_count
        description: Count of licensed users purchased with the customer's subcription.
      - name: dim_usage_ping_id
      - name: ping_created_at
        description: The timestamp at which the usage ping was created.
      - name: ping_created_date_id
      - name: uuid
      - name: hostname
      - name: dim_license_id
      - name: license_md5
      - name: cleaned_version
      - name: umau_28_days_user
      - name: action_monthly_active_users_project_repo_28_days_user
      - name: merge_requests_28_days_user
      - name: projects_with_repositories_enabled_28_days_user
      - name: commit_comment_all_time_event
      - name: source_code_pushes_all_time_event
      - name: ci_pipelines_28_days_user
      - name: ci_internal_pipelines_28_days_user
      - name: ci_builds_28_days_user
      - name: ci_builds_all_time_user
      - name: ci_builds_all_time_event
      - name: ci_runners_all_time_event
      - name: auto_devops_enable_all_time_event
      - name: gitlab_shared_runners_enabled_instance_setting
      - name: container_registry_enabled_instance_setting
      - name: template_repositories_all_time_event
      - name: ci_pipeline_config_repository_28_days_user
      - name: user_unique_users_all_secure_scanners_28_days_user
      - name: user_container_scanning_job_28_days_users
      - name: user_sast_jobs_28_days_user
      - name: user_dast_jobs_28_days_user
      - name: user_dependency_scanning_jobs_28_days_user
      - name: user_license_management_jobs_28_days_user
      - name: user_secret_detection_jobs_28_days_user
      - name: object_store_packages_enabled_instance_setting
      - name: projects_with_packages_all_time_event
      - name: projects_with_packages_28_days_users
      - name: deployments_28_days_users
      - name: releases_28_days_users
      - name: epics_28_days_users
      - name: issues_28_days_users
      - name: instance_user_count_not_aligned
      - name: historical_max_users_not_aligned
      - name: is_seat_link_subscription_in_zuora
        description: Flags rows where the `zuora_subscription_id` from `customers_db_orders_source` is not found in `dim_subscription`.
      - name: is_seat_link_rate_plan_in_zuora
        description: Flags rows where the `product_rate_plan_id` from `customers_db_orders_source` is not found in `dim_product_tier`.
      - name: is_seat_link_active_user_count_available
        description: Flags rows where `active_user_count` is NULL in source.
      - name: is_usage_ping_license_mapped_to_subscription
      - name: is_usage_ping_license_subscription_id_valid
      - name: is_data_in_subscription_month
        description: Flags rows where there is Usage Ping data and/or Seat Link data present

  - name: mart_product_usage_wave_1_3_metrics_monthly
    description: '{{ doc("mart_product_usage_wave_1_3_metrics_monthly") }}'
    columns:
      - name: dim_subscription_id
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: dim_subscription_id_original
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: dim_billing_account_id
        description: Returns unknown ID (MD5(-1)) if the `account_id` from `fct_product_usage_wave_1_3_metrics_monthly` is not found in `dim_billing_account`.
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: dim_crm_account_id
        description: Returns unknown ID (MD5(-1)) if the `dim_crm_account_id` from `dim_billing_account` is not found in `dim_crm_account`.
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: snapshot_month
        description: Month from which Usage Ping and/or Seat Link data is reported (reported as the first day of the month - '2020-01-01').
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: snapshot_date_id
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: seat_link_report_date
        description: Day on which Seat Link usage data is reported. Should always be last day of month for historical months.
      - name: seat_link_report_date_id
      - name: license_utilization
        description: Number of activated seats (`active_user_count`) divided by the number of purchased seats (`license_user_count`) on the subscription.
      - name: active_user_count
        description: Count of active users currently on the customer's subcription. It is possible for a customer to opt out of sending this information to GitLab.
      - name: max_historical_user_count
        description: Maximum active user count ever reported over the lifetime of the customer's subcription.
      - name: license_user_count
        description: Count of licensed users purchased with the customer's subcription.
      - name: dim_usage_ping_id
      - name: ping_created_at
        description: The timestamp at which the usage ping was created.
      - name: ping_created_date_id
      - name: uuid
      - name: hostname
      - name: dim_license_id
      - name: license_md5
      - name: cleaned_version
      - name: umau_28_days_user
      - name: action_monthly_active_users_project_repo_28_days_user
      - name: merge_requests_28_days_user
      - name: projects_with_repositories_enabled_28_days_user
      - name: commit_comment_all_time_event
      - name: source_code_pushes_all_time_event
      - name: ci_pipelines_28_days_user
      - name: ci_internal_pipelines_28_days_user
      - name: ci_builds_28_days_user
      - name: ci_builds_all_time_user
      - name: ci_builds_all_time_event
      - name: ci_runners_all_time_event
      - name: auto_devops_enable_all_time_event
      - name: gitlab_shared_runners_enabled_instance_setting
      - name: container_registry_enabled_instance_setting
      - name: template_repositories_all_time_event
      - name: ci_pipeline_config_repository_28_days_user
      - name: user_unique_users_all_secure_scanners_28_days_user
      - name: user_container_scanning_job_28_days_users
      - name: user_sast_jobs_28_days_user
      - name: user_dast_jobs_28_days_user
      - name: user_dependency_scanning_jobs_28_days_user
      - name: user_license_management_jobs_28_days_user
      - name: user_secret_detection_jobs_28_days_user
      - name: object_store_packages_enabled_instance_setting
      - name: projects_with_packages_all_time_event
      - name: projects_with_packages_28_days_users
      - name: deployments_28_days_users
      - name: releases_28_days_users
      - name: epics_28_days_users
      - name: issues_28_days_users
      - name: instance_user_count_not_aligned
      - name: historical_max_users_not_aligned
      - name: is_seat_link_subscription_in_zuora
        description: Flags rows where the `zuora_subscription_id` from `customers_db_orders_source` is not found in `dim_subscription`.
      - name: is_seat_link_rate_plan_in_zuora
        description: Flags rows where the `product_rate_plan_id` from `customers_db_orders_source` is not found in `dim_product_tier`.
      - name: is_seat_link_active_user_count_available
        description: Flags rows where `active_user_count` is NULL in source.
      - name: is_usage_ping_license_mapped_to_subscription
      - name: is_usage_ping_license_subscription_id_valid
      - name: is_data_in_subscription_month
        description: Flags rows where there is Usage Ping data and/or Seat Link data present

  - name: mart_product_usage_wave_1_3_metrics_monthly_diff
    description: '{{ doc("mart_product_usage_wave_1_3_metrics_monthly_diff") }}'
    columns:
      - name: dim_subscription_id
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: dim_subscription_id_original
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: dim_billing_account_id
        description: Returns unknown ID (MD5(-1)) if the `account_id` from `fct_product_usage_wave_1_3_metrics_monthly` is not found in `dim_billing_account`.
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: snapshot_month
        description: Month from which Usage Ping and/or Seat Link data is reported (reported as the first day of the month - '2020-01-01').
        tests:
          - not_null
        tags: ["tdf", "common", "gainsight"]
      - name: uuid
      - name: hostname
      - name: commit_comment_all_time_event
      - name: commit_comment_since_last_ping
      - name: commit_comment_normalized_monthly
      - name: source_code_pushes_all_time_event
      - name: source_code_pushes_since_last_ping
      - name: source_code_pushes_normalized_monthly
      - name: ci_builds_all_time_event
      - name: ci_builds_since_last_ping
      - name: ci_builds_normalized_monthly
      - name: ci_runners_all_time_event
      - name: ci_runners_since_last_ping
      - name: ci_runners_normalized_monthly
      - name: template_repositories_all_time_event
      - name: template_repositories_since_last_ping
      - name: template_repositories_normalized_monthly
      - name: projects_with_packages_all_time_event
      - name: projects_with_packages_since_last_ping
      - name: projects_with_packages_normalized_monthly
      - name: auto_devops_enable_all_time_event
      - name: auto_devops_enable_since_last_ping
      - name: auto_devops_enable_normalized_monthly
      - name: ci_builds_all_time_user
      - name: ci_builds_since_last_ping

  - name: pump_hash_marketing_contact
    description: '{{ doc("pump_hash_marketing_contact") }}'