version: 2

models:
  - name: pump_marketing_contact
    description: '{{ doc("pump_marketing_contact") }}'
    columns:
      - name: company_name
        description: Mapped to `Company` in Marketo
      - name: country
        description: Mapped to `Country` in Marketo
      - name: customer_db_confirmed_date
        description: Mapped to `CDB_Customer_DB_Confirmed_Date__c` in Marketo
      - name: customer_db_created_date
        description: Mapped to `CDB_Customer_DB_Created_Date__c` in Marketo
      - name: customer_db_customer_id
        description: Mapped to `CDB_Customer_DB_Customer_ID__c` in Marketo
      - name: days_since_saas_signup
        description: Mapped to `CDB_Days_Since_SaaS_Signup__c` in Marketo
      - name: days_since_saas_trial_ended
        description: Mapped to `CDB_Days_Since_SaaS_Trial_Ended__c` in Marketo
      - name: days_since_self_managed_owner_signup
        description: Mapped to `CDB_Days_Since_Self_Managed_Owner_Signup__c` in Marketo
      - name: dim_marketing_contact_id
        description: Mapped to `CDB_Dim_Marketing_Contact_ID__c` in Marketo
      - name: email_address
        description: Mapped to `Email` in Marketo
      - name: first_name
        description: Mapped to `FirstName` in Marketo
      - name: gitlab_dotcom_active_state
        description: Mapped to `CDB_GitLab_com_Active_State__c` in Marketo
      - name: gitlab_dotcom_confirmed_date
        description: Mapped to `CDB_GitLab_com_Confirmed_Date__c` in Marketo
      - name: gitlab_dotcom_created_date
        description: Mapped to `CDB_GitLab_com_Created_Date__c` in Marketo
      - name: gitlab_dotcom_email_opted_in
        description: Mapped to `CDB_GitLab_com_Email_Opted_in__c` in Marketo
      - name: gitlab_dotcom_last_login_date
        description: Mapped to `CDB_GitLab_com_Last_Login_Date__c` in Marketo
      - name: gitlab_dotcom_user_id
        description: Mapped to `CDB_GitLab_com_User_ID__c` in Marketo
      - name: gitlab_user_name
        description: Mapped to `CDB_GitLab_com_User_Name__c` in Marketo
      - name: group_member_of_saas_bronze_tier
        description: Mapped to `CDB_Group_Member_of_SaaS_Bronze_Tier__c` in Marketo
      - name: group_member_of_saas_free_tier
        description: Mapped to `CDB_Group_Member_of_SaaS_Free_Tier__c` in Marketo
      - name: group_member_of_saas_premium_tier
        description: Mapped to `CDB_Group_Member_of_SaaS_Premium_Tier__c` in Marketo
      - name: group_member_of_saas_trial
        description: Mapped to `CDB_Group_Member_of_SaaS_Trial__c` in Marketo
      - name: group_member_of_saas_ultimate_tier
        description: Mapped to `CDB_Group_Member_of_SaaS_Ultimate_Tier__c` in Marketo
      - name: group_owner_of_saas_bronze_tier
        description: Mapped to `CDB_Group_Owner_of_SaaS_Bronze_Tier__c` in Marketo
      - name: group_owner_of_saas_free_tier
        description: Mapped to `CDB_Group_Owner_of_SaaS_Free_Tier__c` in Marketo
      - name: group_owner_of_saas_premium_tier
        description: Mapped to `CDB_Group_Owner_of_SaaS_Premium_Tier__c` in Marketo
      - name: group_owner_of_saas_trial
        description: Mapped to `CDB_Group_Owner_of_SaaS_Trial__c` in Marketo
      - name: group_owner_of_saas_ultimate_tier
        description: Mapped to `CDB_Group_Owner_of_SaaS_Ultimate_Tier__c` in Marketo
      - name: individual_namespace_is_saas_bronze_tier
        description: Mapped to `CDB_Ind_Namespace_is_SaaS_Bronze_Tier__c` in Marketo
      - name: individual_namespace_is_saas_free_tier
        description: Mapped to `CDB_Ind_Namespace_is_SaaS_Free_Tier__c` in Marketo
      - name: individual_namespace_is_saas_premium_tier
        description: Mapped to `CDB_Ind_Namespace_is_SaaS_Premium_Tie__c` in Marketo
      - name: individual_namespace_is_saas_trial
        description: Mapped to `CDB_Ind_Namespace_is_SaaS_Trial__c` in Marketo
      - name: individual_namespace_is_saas_ultimate_tier
        description: Mapped to `CDB_Ind_Namespace_is_SaaS_Ultimate_Ti__c` in Marketo
      - name: is_customer_db_owner
        description: Mapped to `CDB_Is_Customer_DB_Owner__c` in Marketo
      - name: is_customer_db_user
        description: Mapped to `CDB_Is_Customer_DB_User__c` in Marketo
      - name: is_gitlab_dotcom_user
        description: Mapped to `CDB_Is_GitLab_com_User__c` in Marketo
      - name: is_group_namespace_member
        description: Mapped to `CDB_Is_Group_Namespace_Member__c` in Marketo
      - name: is_group_namespace_owner
        description: Mapped to `CDB_Is_Group_Namespace_Owner__c` in Marketo
      - name: is_individual_namespace_owner
        description: Mapped to `CDB_Is_Individual_Namespace_Owner__c` in Marketo
      - name: is_self_managed_premium_tier
        description: Mapped to `CDB_Is_Self_Managed_Premium_Tier__c` in Marketo
      - name: is_self_managed_starter_tier
        description: Mapped to `CDB_Is_Self_Managed_Starter_Tier__c` in Marketo
      - name: is_self_managed_ultimate_tier
        description: Mapped to `CDB_Is_Self_Managed_Ultimate_Tier__c` in Marketo
      - name: is_sfdc_lead_contact
        description: Already available in Marketo
      - name: is_sfdc_opted_out
        description: Already available in Marketo
      - name: is_zuora_billing_contact
        description: In Salesforce
      - name: job_title
        description: Mapped to `Title` in Marketo
      - name: last_name
        description: Mapped to `LastName` in Marketo
      - name: responsible_for_free_tier_only
        description: Mapped to `CDB_Responsible_for_Free_Tier_Only__c` in Marketo
      - name: responsible_for_group_saas_bronze_tier
        description: Mapped to `CDB_Resp_for_Group_Saas_Bronze_Tier__c` in Marketo
      - name: responsible_for_group_saas_free_tier
        description: Mapped to `CDB_Resp_for_Group_Saas_Free_Tier__c` in Marketo
      - name: responsible_for_group_saas_premium_tier
        description: Mapped to `CDB_Resp_for_Group_Saas_Premium_Tier__c` in Marketo
      - name: responsible_for_group_saas_trial
        description: Mapped to `CDB_Resp_for_Group_SaaS_Trial__c` in Marketo
      - name: responsible_for_group_saas_ultimate_tier
        description: Mapped to `CDB_Resp_for_Group_Saas_Ultimate_Tier__c` in Marketo
      - name: sfdc_created_date
        description: Already available in Marketo
      - name: sfdc_lead_contact
        description: Already available in Marketo
      - name: sfdc_parent_sales_segment
        description: Already available in Marketo
      - name: zuora_active_state
        description: In Salesforce
      - name: zuora_contact_id
        description: In Salesforce
      - name: zuora_created_date
        description: In Salesforce
      - name: last_changed
        description: use in pump copy command, but not mapped to Marketo
  - name: pump_subscription_product_usage
    description: '{{ doc("pump_subscription_product_usage") }}'
