version: 2

sources:
  - name: handbook
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: handbook
    loader: Airflow
    
    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}

    tables:
      - name: handbook_merge_requests
        description: '{{ doc("handbook_merge_requests") }}'
        loaded_at_field: uploaded_at
      - name: values_after_2020_06
        identifier: values_page_git_log
      - name: values_before_2020_06
        identifier: values_page_git_log_before_2020_06
