version: 2

models:
  - name: fct_usage_ping_metrics_status
    description: fct table that gets statistics for the metrics. to understand if the metrics succeeded and failed and how many rows we have per metrics
  - name: wk_saas_usage_ping_instance_flattened
    description: workspace table flattening JSON results contained in saas_usage_ping_instance's column run_results
  - name: wk_saas_usage_ping_instance_redis_metrics
    description: workspace table flattening JSON results contained in instance_redis_metrics    's column run_results
