version: 2

models:
  - name: fct_usage_ping_metrics_status
    description: '{{ doc("fct_usage_ping_metrics_status") }}'
  - name: wk_saas_usage_ping_instance_flattened
    description: '{{ doc("wk_saas_usage_ping_instance_flattened") }}'
    columns:
      - name: saas_usage_ping_gitlab_dotcom_id
        description: unique identifier (combine `ping_date` + `run_results` columns)
        tests:
          - not_null
      - name: ping_date
        description: Actual date when ping is executed and data is extracted into Data Warehouse. This value determinates when data is processed.
        tests:
          - not_null
      - name: metric_path
        description: Metric description / metric name
        tests:
          - not_null
      - name: metric_value
        description: Metric value
        tests:
          - not_null
      - name: metrics_status
        description: Metrics status -lookup from dim_usage_ping_metric
      - name: recorded_at
        description: Value for the metric `recorded_at` in TIMESTAMP format
      - name: version
        description: App version (from the original .json file)
      - name: edition
        description: Edition type (from the original .json file)
      - name: recording_ce_finished_at
        description: Timestamp when CE recording is finished (from the original .json file)
      - name: recording_ee_finished_at
        description: Timestamp when EE recording is finished (from the original .json file)
      - name: uuid
        description: unique number from API (from the original .json file)
  - name: wk_saas_usage_ping_instance_redis_metrics
    description: '{{ doc("wk_saas_usage_ping_instance_redis_metrics") }}'
    columns:
      - name: saas_usage_ping_redis_id
        description: Primary key for instance redis metrics reprsent as unique combination from ping_date + run_id columns
        tests:
          - not_null
      - name: ping_date
        description: Actual date when ping is executed and data is extracted into Data Warehouse. This value determinates when data is processed. 
        tests:
          - not_null
      - name: metric_path
        description: Metric description / metric name
        tests:
          - not_null
      - name: metric_value
        description: Metric value
        tests:
          - not_null
      - name: metrics_status
        description: Metrics status -lookup from dim_usage_ping_metric
      - name: recorded_at
        description: Value for the metric `recorded_at` in TIMESTAMP format
        tests:
          - not_null
      - name: version
        description: App version (from the original .json file)
      - name: edition
        description: Edition type (from the original .json file)
      - name: recording_ce_finished_at
        description: Timestamp when CE recording is finished (from the original .json file)
      - name: recording_ee_finished_at
        description: Timestamp when EE recording is finished (from the original .json file)
      - name: uuid
        description: unique number from API (from the original .json file)
