version: 2

models:
  - name: gitlab_dotcom_bulk_import_entities_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_source_scd") }}'
  - name: gitlab_dotcom_clusters_integration_prometheus_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_source_scd") }}'
  - name: gitlab_dotcom_group_import_states_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_source_scd") }}'
  - name: gitlab_dotcom_lfs_file_locks_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_source_scd") }}'
  - name: gitlab_dotcom_path_locks_dedupe_source
    description: '{{ doc("gitlab_dotcom_dedupe_source_scd") }}'