version: 2

sources:
  - name: full_table_clones
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: snowflake
    loader: Airflow

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: mart_arr_rolled_up
