version: 2

models:
  - name: wk_self_managed_spo
    description: Workspace model that builds a MVC for Self-Managed SPO and SPU KPIs.
    columns:
      - name: organization_id
        tests:
          - not_null
      - name: delivery
        tests:
          - not_null
      - name: organization_type
        tests:
          - not_null
          - accepted_values:
              values: ['Group','Individual']
      - name: active_stage_count
        description: number of active stages for a given organization in a given month


  - name: wk_saas_spo
    description: Workspace model that shows monthly Stages per Organization data on a namespace-level for SaaS.
    columns:
      - name: reporting_month
        tests:
          - not_null
      - name: organization_id
        description: Top-level namespace id.
        tests:
          - not_null
      - name: delivery
        tests:
          - not_null
      - name: organization_type
        tests:
          - not_null
          - accepted_values:
              values: ['Group','Individual','User']
      - name: product_tier
        tests:
          - not_null
      - name: is_paid_product_tier
        tests:
          - not_null
      - name: active_stage_count
        description: number of active stages for a given organization in a given month

  - name: wk_usage_ping_geo_node_usage
    description: Extract and flatten data from the geo nodes
    columns:
      - name: instance_path_id
        tests:
          - not_null
          - unique

  - name: fct_usage_event
    description: ' {{ doc("fct_usage_event") }} '
    columns:
      - name: event_id
        tests:
          - not_null
          - unique

  - name: mart_usage_event
    description: ' {{ doc("mart_usage_event") }} '
    columns:
      - name: event_id
        tests:
          - not_null
          - unique

  - name: mart_usage_namespace_daily
    description: ' {{ doc("mart_usage_namespace_daily") }} '
    columns:
      - name: mart_usage_namespace_id
        tests:
          - not_null
          - unique

  - name: mart_usage_instance_daily
    description: ' {{ doc("mart_usage_instance_daily") }} '
    columns:
      - name: mart_usage_instance_id
        tests:
          - not_null
          - unique

  - name: mart_usage_event_daily
    description: ' {{ doc("mart_usage_event_daily") }} '
    columns:
      - name: mart_usage_event_daily_id
        tests:
          - not_null
          - unique

  - name: mart_usage_event_plan_monthly
    description: ' {{ doc("mart_usage_event_plan_monthly") }} '
    columns:
      - name: mart_usage_event_plan_monthly_id
        tests:
          - not_null
          - unique

  - name: prep_service_ping_instance_flattened
    description: ' {{ doc("prep_service_ping_instance_flattened") }} '
    columns:
      - name: raw_usage_data
        tests:
          - not_null
          - unique

  - name: prep_service_ping_instance
    description: ' {{ doc("prep_service_ping_instance") }} '
    columns:
      - name: prep_service_ping_instance_id
        tests:
          - not_null
          - unique


  - name: fct_service_ping_instance
    description: ' {{ doc("fct_service_ping_instance") }} '
    columns:
      - name: fct_service_ping_instance_id
        tests:
          - not_null
          - unique

  - name: dim_service_ping_instance
    description: ' {{ doc("dim_service_ping_instance") }} '
    columns:
      - name: dim_service_ping_instance_id
        tests:
          - not_null
          - unique

  - name: mart_service_ping_instance
    description: ' {{ doc("dim_service_ping_instance") }} '
    columns:
      - name: mart_service_ping_instance_id
        tests:
          - not_null
          - unique

  - name: mart_xmau_metric_monthly
    description: ' {{ doc("mart_xmau_metric_monthly") }} '
    columns:
      - name: mart_xmau_metric_monthly_id
        tests:
          - not_null
          - unique
