version: 2

sources:
  - name: data_science
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: data_science
    loader: Airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 14, period: day}

    tables:
    - name: pte_scores

