version: 2

models:
  - name: zuora_query_api_users_source
    description: Source layer for Zuora Users
    tests:
    columns:
      - name: zuora_user_id
        tests:
          - not_null
          - unique