CREATE TABLE IF NOT EXISTS RAW.TAP_POSTGRES.GITLAB_DB_GEO_NODES (
    id                                  NUMBER(38,0),
    primary                             BOOLEAN,
    oauth_application_id                NUMBER(38,0),
    enabled                             BOOLEAN,
    access_key                          VARCHAR(16777216),
    encrypted_secret_access_key         VARCHAR(16777216),
    encrypted_secret_access_key_iv      VARCHAR(16777216),
    clone_url_prefix                    VARCHAR(16777216),
    files_max_capacity                  NUMBER(38,0),
    repos_max_capacity                  NUMBER(38,0),
    url                                 VARCHAR(16777216),
    selective_sync_type                 VARCHAR(16777216),
    selective_sync_shards               VARCHAR(16777216),
    verification_max_capacity           NUMBER(38,0),
    minimum_reverification_interval     NUMBER(38,0),
    internal_url                        VARCHAR(16777216),
    name                                VARCHAR(16777216),
    container_repositories_max_capacity NUMBER(38,0),
    created_at                          TIMESTAMP_NTZ(9),
    updated_at                          TIMESTAMP_NTZ(9),
    sync_object_storage                 BOOLEAN,
    _uploaded_at                        TIMESTAMP_NTZ(9)
);
