version: 2

# Data in tables is from test data and is not specifically conformant with the final shape of the data.
# Tests will be added in the next milestone after live data is added to the reports.

models:
  - name: workday_bonus_source
    description: '{{ doc("workday_custom_bonus") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - employee_id
            - workday_id
    columns:
      - name: employee_id
        description: '{{ doc("workday_employee_id") }}'
        tests:
          - not_null

      - name: bonus_date
        description: '{{ doc("workday_bonus_date") }}'
        tests:
          - not_null

      - name: bonus_type
        description: '{{ doc("workday_bonus_type") }}'
        tests:
          - not_null

      - name: uploaded_at
        description: '{{ doc("workday_uploaded_at") }}'
      - name: initiated_at
        description: '{{ doc("workday_initiated_at") }}'
      - name: workday_id
        description: '{{ doc("workday_workday_id") }}'
        tests:
          - unique

  - name: workday_compensation_source
    description: '{{ doc("workday_compensation") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - employee_id
            - effective_date
            - compensation_type
            - initiated_at
    columns:
      - name: employee_id
        description: '{{ doc("workday_employee_id") }}'
        tests:
          - not_null

      - name: effective_date
        description: '{{ doc("workday_effective_date") }}'
        tests:
          - not_null

      - name: compensation_type
        description: '{{ doc("workday_compensation_type") }}'
        tests:
          - not_null

      - name: compensation_change_reason
        description: '{{ doc("workday_compensation_change_reason") }}'
        tests:
          - not_null

      - name: pay_rate
        description: '{{ doc("workday_pay_rate") }}'


      - name: compensation_value
        description: '{{ doc("workday_compensation_value") }}'


      - name: compensation_currency
        description: '{{ doc("workday_compensation_currency") }}'


      - name: conversion_rate_local_to_usd
        description: '{{ doc("workday_conversion_rate_local_to_usd") }}'


      - name: compensation_currency_usd
        description: '{{ doc("workday_compensation_currency_usd") }}'


      - name: compensation_value_usd
        description: '{{ doc("workday_compensation_value_usd") }}'
        tests:
          - not_null
      - name: pay_frequency
        description: '{{ doc("workday_pay_frequency") }}'
      - name: per_pay_period_amount
        description: '{{ doc("workday_per_pay_period_amount") }}'

      - name: initiated_at
        description: '{{ doc("workday_initiated_at") }}'

      - name: uploaded_at
        description: '{{ doc("workday_uploaded_at") }}'

  - name: workday_directory_source
    description: '{{ doc("workday_directory") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - employee_id
            - valid_from

    columns:
      - name: employee_id
        description: '{{ doc("workday_employee_id") }}'
        tests:
          - not_null

      - name: work_email
        description: '{{ doc("workday_work_email") }}'
        
      - name: full_name
        description: '{{ doc("workday_full_name") }}'
        
      - name: job_title
        description: '{{ doc("workday_job_title") }}'
        
      - name: supervisor
        description: '{{ doc("workday_supervisor") }}'
        
      - name: uploaded_at
        description: '{{ doc("workday_uploaded_at") }}'

      - name: valid_from
      - name: valid_to
      - name: is_current

  - name: workday_emergency_contacts_source
    description: '{{ doc("workday_employment_status") }}'

    columns:
      - name: employee_id
        description: '{{ doc("workday_employee_id") }}'
        tests:
          - not_null
          - unique
  
      - name: full_name
        description: '{{ doc("workday_full_name") }}'

      - name: home_phone
        description: '{{ doc("workday_home_phone") }}'

      - name: mobile_phone
        description: '{{ doc("workday_mobile_phone") }}'

      - name: work_phone
        description: '{{ doc("workday_work_phone") }}'

      - name: uploaded_at
        description: '{{ doc("workday_uploaded_at") }}'

      - name: initiated_at
        description: '{{ doc("workday_initiated_at") }}'

  - name: workday_employee_mapping_source
    description: '{{ doc("workday_employee_mapping") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - employee_id
            - uploaded_at

    columns:
      - name: employee_id
        description: '{{ doc("workday_employee_id") }}'
        tests:
          - not_null

      - name: employment_history_status
        description: '{{ doc("workday_employment_history_status") }}'
      - name: employee_status_date
        description: '{{ doc("workday_employee_status_date") }}'
      - name: cost_center
        description: '{{ doc("workday_cost_center") }}'
      - name: last_name
        description: '{{ doc("workday_last_name") }}'
      - name: first_name
        description: '{{ doc("workday_first_name") }}'
      - name: region
        description: '{{ doc("workday_region") }}'
      - name: hire_date
        description: '{{ doc("workday_hire_date") }}'
      - name: country
        description: '{{ doc("workday_country") }}'
      - name: greenhouse_candidate_id
        description: '{{ doc("workday_greenhouse_candidate_id") }}'
      - name: gender
        description: '{{ doc("workday_gender") }}'
      - name: job_role
        description: '{{ doc("workday_job_role") }}'
      - name: gender_dropdown
        description: '{{ doc("workday_gender_dropdown") }}'
      - name: date_of_birth
        description: '{{ doc("workday_date_of_birth") }}'
      - name: job_grade
        description: '{{ doc("workday_job_grade") }}'
      - name: pay_frequency
        description: '{{ doc("workday_pay_frequency") }}'
      - name: age
        description: '{{ doc("workday_age") }}'
      - name: jobtitle_speciality_single_select
        description: '{{ doc("workday_jobtitle_speciality_single_select") }}'
      - name: ethnicity
        description: '{{ doc("workday_ethnicity") }}'
      - name: jobtitle_speciality_multi_select
        description: '{{ doc("workday_jobtitle_speciality_multi_select") }}'
      - name: gitlab_username
        description: '{{ doc("workday_gitlab_username") }}'
      - name: sales_geo_differential
        description: '{{ doc("workday_sales_geo_differential") }}'
      - name: locality
        description: '{{ doc("workday_locality") }}'
      - name: termination_date
        description: '{{ doc("workday_termination_date") }}'
      - name: nationality
        description: '{{ doc("workday_nationality") }}'
      - name: uploaded_at
        description: '{{ doc("workday_uploaded_at") }}'
      - name: valid_from
      - name: valid_to
      - name: is_current


  - name: workday_employment_status_source
    description: '{{ doc("workday_employment_status") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - employee_id
            - effective_date

    columns:
      - name: employee_id
        description: '{{ doc("workday_employee_id") }}'
        tests:
          - not_null

      - name: effective_date
        description: '{{ doc("workday_effective_date") }}'
      - name: employment_status
        description: '{{ doc("workday_employment_status_column") }}'
      - name: termination_type
        description: '{{ doc("workday_termination_type") }}'
      - name: uploaded_at
        description: '{{ doc("workday_uploaded_at") }}'
      - name: initiated_at
        description: '{{ doc("workday_initiated_at") }}'

  - name: workday_job_info_source
    description: '{{ doc("workday_job_info") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - employee_id
            - effective_date
            - initiated_at

    columns:
      - name: employee_id
        description: '{{ doc("workday_employee_id") }}'
        tests:
          - not_null

      - name: business_process_event
        description: '{{ doc("workday_business_process_event") }}'
      - name: department
        description: '{{ doc("workday_department") }}'
      - name: division
        description: '{{ doc("workday_division") }}'
      - name: effective_date
        description: '{{ doc("workday_effective_date") }}'
        tests:
          - not_null
      - name: entity
        description: '{{ doc("workday_entity") }}'
      - name: job_title
        description: '{{ doc("workday_job_title") }}'
      - name: reports_to
        description: '{{ doc("workday_reports_to") }}'
      - name: uploaded_at
        description: '{{ doc("workday_uploaded_at") }}'
      - name: initiated_at
        description: '{{ doc("workday_initiated_at") }}'
        tests:
          - not_null

  - name: workday_on_target_earnings_source
    description: '{{ doc("workday_on_target_earnings") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - employee_id
            - effective_date
            - initiated_at

    columns:
      - name: employee_id
        description: '{{ doc("workday_employee_id") }}'
        tests:
          - not_null

      - name: annual_amount_local
        description: '{{ doc("workday_annual_amount_local") }}'
      - name: annual_amount_local_currency_code
        description: '{{ doc("workday_annual_amount_local_currency_code") }}'
      - name: annual_amount_usd_value
        description: '{{ doc("workday_annual_amount_usd_value") }}'
      - name: effective_date
        description: '{{ doc("workday_effective_date") }}'
      - name: ote_local
        description: '{{ doc("workday_ote_local") }}'
      - name: ote_local_currency_code
        description: '{{ doc("workday_ote_local_currency_code") }}'
      - name: ote_type
        description: '{{ doc("workday_ote_type") }}'
      - name: ote_usd
        description: '{{ doc("workday_ote_usd") }}'
      - name: uploaded_at
        description: '{{ doc("workday_uploaded_at") }}'
      - name: initiated_at
        description: '{{ doc("workday_initiated_at") }}'

  - name: blended_bonus_source
    columns:
      - name: unique_filter_key
        tests:
          - unique

  - name: blended_emergency_contacts_source
    columns:
      - name: unique_filter_key
        tests:
          - unique

  - name: blended_employee_mapping_source
    columns:
      - name: unique_filter_key
        tests:
          - unique

  - name: blended_employment_status_source
    columns:
      - name: unique_filter_key
        tests:
          - unique

  - name: blended_job_info_source
    columns:
      - name: unique_filter_key
        tests:
          - unique

  - name: blended_on_target_earnings_source
    columns:
      - name: unique_filter_key
        tests:
          - unique

  - name: blended_compensation_source
    columns:
      - name: unique_filter_key
        tests:
          - unique

  - name: blended_currency_conversion_source
    columns:
      - name: unique_filter_key
        tests:
          - unique