version: 2

models:
    - name: qualtrics_api_formatted_contacts
      description: GitLab dotcom users table formatted for quick lookup and push to Qualtrics
      columns:
        - name: email_address
          tests:
            - not_null
        - name: first_name
        - name: last_name
        - name: phone_number
        - name: user_id
          tests:
            - unique
    - name: qualtrics_contact_mailing_send
      description: 'All mailings sent to individual Qualtrics contacts, as well as the time in which they were sent.'
      columns:
        - name: contact_email
          tests:
            - not_null
        - name: mailing_sent_at
          tests:
            - not_null
        - name: survey_name
          tests:
            - not_null
    - name: qualtrics_nps_answers
      description: Answers to various nps survey questions joined with various information about the user and their response.
      columns:
        - name: distribution_channel
        - name: has_finished_survey
          tests:
            - not_null
        - name: question_description
        - name: question_id
            - not_null
        - name: question_response
        - name: response_id
        - name: survey_start_date
        - name: survey_end_date
          description: The last recorded time a user interacts with the survey.
        - name: response_recorded_at
          description: In qualtrics, if a user interacts with a survey and then there is no further interaction the recorded date will show up as 7 days after the survey end date and turn the survey into a completed response.
          tests:
            - not_null
        - name: user_language
        - name: user_plan
    - name: qualtrics_nps_scores
      description: Just the scores and reasons from the `qualtrics_nps_answers` model.
      columns:
        - name: response_id
          tests:
            - unique
        - name: nps_reason
          description: The reason given with the score (optional).
        - name: nps_score
          tests:
            - not_null
        - name: nps_bucket_text
          tests:
            - not_null
        - name: nps_bucket_integer
          description: Take the average of this column to get the "NPS Score".
          tests:
            - not_null
        - name: user_plan
          description: The product plan of the user as recorded in Qualtrics at the time of the survey.
    - name: qualtrics_post_purchase_survey_answers
      description: One record for each choice selected for each of the questions from the post purchase survey.
      columns:
        - name: response_id
        - name: question_id
        - name: question_description
        - name: answer_display
        - name: answer_id
        - name: distribution_channel
        - name: has_finished_survey
        - name: survey_start_date
        - name: survey_end_date
        - name: response_recorded_at
        - name: user_language
        - name: user_plan
    - name: qualtrics_post_purchase_survey_responses
      description: One record for each survey response.
      columns:
        - name: is_finished
        - name: recorded_at
        - name: response_id
          tests: 
            - not_null
        - name: started_at
        - name: user_plan
    - name: qualtrics_survey_invitation_emails_sent
      description: One record for each survey along with how many invitation emails were sent for that survey
      columns:
        - name: number_of_emails_sent
          tests:
            - not_null
        - name: survey_id
          tests:
            - not_null
            - unique