version: 2

models:
  - name: mart_arr
    description: '{{ doc("mart_arr") }}'
    columns:
      - name: arr
        description: "Calculated as 12 * MRR value"
      - name: primary_key
        tests:
            - not_null
            - unique
      - name: is_reseller
        description: Identify whether a crm_account is a reseller.
      - name: subscription_sales_type
        description: Identifies whether a subscription is Sales-Assisted or Self-Service / Web Direct.

  - name: mart_arr_snapshots
    description: Daily snapshots of MRR/ARR by month values per customer, subscription and product
    columns:
      - name: primary_key
        tests:
          - not_null
        tags: ["tdf", "mart", "arr"]

  - name: mart_crm_opportunity
    description: Model with single pane of glass sales and marketing metrics.
    columns:
      - name: crm_opportunity_id
        tests:
            - not_null
            - unique
        tags: ["tdf", "mart", "sales_funnel"]

  - name: mart_crm_person
    description: Model with person and MQL business logic.
    columns:
      - name: dim_crm_person_id
        tests:
            - not_null
            - unique
        tags: ["tdf", "mart", "sales_funnel"]

  - name: mart_sales_funnel_target
    description: Model with Sales targets used for planning the go to market Sales and Marketing motion.
    columns:
      - name: sales_funnel_target_id
        tests:
            - not_null
            - unique
        tags: ["tdf", "mart", "sales_funnel"]

  - name: mart_discount_arr
    description: Model with Invoiced ARR used to calculate discounts across various dimensions.
    columns:
      - name: primary_key
        description: Unique identifier of a product charge on the invoice amortized by month.
        tests:
            - not_null
            - unique
        tags: ["tdf", "mart", "arr"]
      - name: is_myb
        description: Identifies if a subscription charge is for a multiple year term.
      - name: current_term_months
        description: Term of the subscription in months.
      - name: current_term_years
        description: Term of the subscription in years. Rounds to the one decimal point. For examples, an 18 month term subscription will be a 1.5 year term.
      - name: prepaid_myb
        description: Identifies if a MYB deal has more than 1 year paid on the subscription. The flag does NOT identify how years have been prepaid or if the subscription has been prepaid in full.

  - name: mart_delta_arr_parent_month
    description: "Mart table by month pursuant to the ARR Analysis Framework at the parent customer level"
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags: ["tdf", "mart", "arr"]

  - name: mart_delta_arr_parent_product_month
    description: "Mart table by month pursuant to the ARR Analysis Framework at the parent customer || product category level"
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags: ["tdf", "mart", "arr"]
      - name: product_category
        tests:
          - not_null
        tags: ["tdf", "mart", "arr"]
      - name: delivery
        tests:
          - not_null
        tags: ["tdf", "mart", "arr"]
      - name: product_ranking
        tests:
          - not_null
        tags: ["tdf", "mart", "arr"]

  - name: mart_delta_arr_subscription_month
    description: "Mart table by month purusant to the ARR Analysis Framework at the subscription level"
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags: ["tdf", "mart", "arr"]

  - name: mart_retention_parent_account
    description: "Mart table to support drillable retention analysis"

  - name: mart_retention_parent_account_product
    description: "Mart table to support retention analysis at the ultimate_parent_account || product level."
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
        tags: ["tdf", "mart", "arr"]

  - name: usage_ping_mart
    description: '{{ doc("usage_ping_mart") }}'
    columns:
      - name: usage_ping_id
        tests:
          - not_null
          - unique
      - name: uuid
        tests:
          - not_null
      - name: date_id
        tests:
          - not_null
