version: 2

sources:
  - name: gitlab_ops
    tags: ["tdf", "gitlab_ops"]
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: tap_postgres
    loaded_at_field: DATEADD(sec, _uploaded_at, '1970-01-01')
    loader: Airflow, tap_postgres
    description: Analytics read replica for gitlab ops data. [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/2654)

    quoting:
      database: true
      schema: false
      identifier: false

    freshness: null

    tables:
      - name: ci_pipelines
        identifier: gitlab_ops_db_ci_pipelines
      - name: ci_stages
        identifier: gitlab_ops_db_ci_stages
      - name: label_links
        identifier: gitlab_ops_db_label_links
      - name: labels
        identifier: gitlab_ops_db_labels
      - name: members
        identifier: gitlab_ops_db_members
      - name: merge_requests
        identifier: gitlab_ops_db_merge_requests
      - name: projects
        identifier: gitlab_ops_db_projects
      - name: users
        identifier: gitlab_ops_db_users
