version: 2

models:
  - name: prep_usage_ping
    description: '{{ doc("prep_usage_ping") }}'
    columns:
      - name: dim_usage_ping_id
        description: This is a unique identifier for a usage ping sent by an instance. 
        tests:
          - not_null
          - unique
        tags: ["tdf", "gainsight"]
      - name: dim_product_tier_id
        description: The unique ID of a product tier determined in dim_product_tier.
      - name: ping_created_at
        description: The timestamp at which the usage ping was created_at 
      - name: ping_created_at_28_days_earlier
        description: The timestamp at which the usage ping was created_at minus 28 days for the monthly metric time period 
      - name: ping_created_at_year
        description: The year ('2017') the ping was created at
      - name: ping_created_at_month
        description: The month ('2017-01-01') the ping was created at
      - name: ping_created_at_week
        description: The week start ('2017-01-01') the ping was created at
      - name: ping_created_at_date
        description: The day the ping was created at (removes the extra time information in the timestamp)
      - name: raw_usage_data_id
        description: The JOIN key to version_raw_usage_data_source https://dbt.gitlabdata.com/#!/model/model.gitlab_snowflake.version_raw_usage_data_source
      - name: raw_usage_data_payload
        description: Either the original payload value or a reconstructed value. See https://gitlab.com/gitlab-data/analytics/-/merge_requests/4064/diffs#bc1d7221ae33626053b22854f3ecbbfff3ffe633 for rationale. 
      - name: license_md5
        description: JOIN key to the dim_license table on license_md5 OR the original source table from licenseDot 
      - name: original_edition
        description: The original `edition` value that comes on the usage ping. This has a lot of data inaccuracies
      - name: edition
        description: The cleaned `edition` value to remove data inaccuracies 
      - name: main_edition
        description: segmentation for Edition. Values - CE, EE
      - name: product_tier
        description: segmentation for Product Tier. Values - Core (CE, EE), Starter, Premium, Ultimate, NULL
      - name: main_edition_product_tier
        description: segmentation for the product tier, including separate records for Core CE and Core EE
      - name: cleaned_version 
        description: Cleaned up version field with -  'REGEXP_REPLACE(NULLIF(version, ''), '[^0-9.]+')'
      - name: version_is_prerelease 
        description: If the version has a 'pre' value appended (IFF(version ILIKE '%-pre', True, False))
      - name: major_version 
        description: The major release number for that version (SPLIT_PART(cleaned_version, '.', 1)::NUMBER)
      - name: minor_version  
        description: The minor release number for that version (SPLIT_PART(cleaned_version, '.', 2)::NUMBER)
      - name: major_minor_version  
        description: Concatenation of the major and minor version (major_version || '.' || minor_version) 
      - name: ping_source
        description: segmentation for SaaS data (from the self-managed instance that hosts the SaaS GitLab.com website) and data sent from customer self-managed instances
      - name: is_internal
        description: boolean flag that indicates that the instance is used by the company or a GitLab team member
      - name: is_staging
        description: DRAFT - need to better identify instances used for staging environments
      - name: country_name
        description: The name of the country where the instance reported the ping from 
      - name: iso_2_country_code
        description: The iso 2 country code where the instance reported the ping from 
      - name: iso_3_country_code
        description: The iso 3 country code where the instance reported the ping from 


  - name: prep_usage_ping_no_license_key
    description: '{{ doc("prep_usage_ping_no_license_key") }}'
    columns:
      - name: dim_usage_ping_id
        description: JOIN key to dim_usage_pings and prep_usage_pings. Represents a single usage ping. 
      - name: ping_created_at
        description: The timestamp at which the usage ping was created_at 
      - name: ping_created_at_28_days_earlier
        description: The timestamp at which the usage ping was created_at minus 28 days for the monthly metric time period 
      - name: ping_created_at_year
        description: The year ('2017') the ping was created at
      - name: ping_created_at_month
        description: The month ('2017-01-01') the ping was created at
      - name: ping_created_at_week
        description: The week start ('2017-01-01') the ping was created at
      - name: ping_created_at_date
        description: The day the ping was created at (removes the extra time information in the timestamp)

  - name: prep_usage_ping_saas_dates
    description: '{{ doc("prep_usage_ping_saas_dates") }}'
    columns:
      - name: dim_usage_ping_id
        description: JOIN key to dim_usage_pings and prep_usage_pings. Represents a single usage ping. 
      - name: ping_created_at_date
        description: The day the ping was created at (removes the extra time information in the timestamp)
      - name: ping_created_at_28_days_earlier
        description: The timestamp at which the usage ping was created_at minus 28 days for the monthly metric time period 
      - name: ping_created_at_year
        description: The year ('2017') the ping was created at
      - name: ping_created_at_month
        description: The month ('2017-01-01') the ping was created at
      - name: ping_created_at_week
        description: The week start ('2017-01-01') the ping was created at 

  - name: prep_usage_ping_subscription_mapped
    description: '{{ doc("prep_usage_ping_subscription_mapped") }}'
    columns:
      - name: dim_usage_ping_id
        description: JOIN key to dim_usage_pings and prep_usage_pings. Represents a single usage ping. 
      - name: license_md5 
        description: JOIN key to dim_licenses and dim_license 
      - name: subscription_id 
        description: JOIN key to dim_subscription 
      - name: ping_created_at
        description: The timestamp at which the usage ping was created_at 
      - name: ping_created_at_28_days_earlier
        description: The timestamp at which the usage ping was created_at minus 28 days for the monthly metric time period 
      - name: ping_created_at_year
        description: The year ('2017') the ping was created at
      - name: ping_created_at_month
        description: The month ('2017-01-01') the ping was created at
      - name: ping_created_at_week
        description: The week start ('2017-01-01') the ping was created at
      - name: ping_created_at_date
        description: The day the ping was created at (removes the extra time information in the timestamp)

  - name: prep_usage_ping_subscription_mapped_wave_2_3_metrics
    description: '{{ doc("prep_usage_ping_subscription_mapped_wave_2_3_metrics") }}'
    columns:
      - name: dim_usage_ping_id
        description: JOIN key to dim_usage_pings and prep_usage_pings. Represents a single usage ping. 
      - name: ping_created_at
        description: The timestamp at which the usage ping was created_at 
      - name: ping_created_at_28_days_earlier
        description: The timestamp at which the usage ping was created_at minus 28 days for the monthly metric time period 
      - name: ping_created_at_year
        description: The year ('2017') the ping was created at
      - name: ping_created_at_month
        description: The month ('2017-01-01') the ping was created at
      - name: ping_created_at_week
        description: The week start ('2017-01-01') the ping was created at
      - name: ping_created_at_date
        description: The day the ping was created at (removes the extra time information in the timestamp)
      - name: uuid
      - name: ping_source
      - name: instance_version
      - name: cleaned_version
      - name: version_is_prerelease
      - name: major_version
      - name: minor_version
      - name: major_minor_version
      - name: product_tier
      - name: main_edition_product_tier
      - name: hostname
      - name: host_id
      - name: installation_type
      - name: is_internal
      - name: is_staging
      - name: instance_user_count
      - name: historical_max_users
      - name: license_md5 
        description: JOIN key to dim_licenses and dim_license 
      - name: is_usage_ping_license_in_licenseDot
      - name: dim_license_id
      - name: dim_subscription_id
        description: JOIN key to dim_subscription 
      - name: is_license_mapped_to_subscription
      - name: is_license_subscription_id_valid
      - name: dim_crm_account_id
      - name: dim_parent_crm_account_id
      - name: umau_28_days_user
      - name: action_monthly_active_users_project_repo_28_days_user
      - name: merge_requests_28_days_user
      - name: projects_with_repositories_enabled_28_days_user
      - name: commit_comment_all_time_event
      - name: source_code_pushes_all_time_event
      - name: ci_pipelines_28_days_user
      - name: ci_internal_pipelines_28_days_user
      - name: ci_builds_28_days_user
      - name: ci_builds_all_time_user
      - name: ci_builds_all_time_event
      - name: ci_runners_all_time_event
      - name: auto_devops_enabled_all_time_event
      - name: gitlab_shared_runners_enabled_instance_setting
      - name: container_registry_enabled_instance_setting
      - name: template_repositories_all_time_event
      - name: ci_pipeline_config_repository_28_days_user
      - name: user_unique_users_all_secure_scanners_28_days_user
      - name: user_container_scanning_job_28_days_user
      - name: user_sast_jobs_28_days_user
      - name: user_dast_jobs_28_days_user
      - name: user_dependency_scanning_jobs_28_days_user
      - name: user_license_management_jobs_28_days_user
      - name: user_secret_detection_jobs_28_days_user
      - name: object_store_packages_enabled_instance_setting
      - name: projects_with_packages_all_time_event
      - name: projects_with_packages_28_days_user
      - name: deployments_28_days_user
      - name: releases_28_days_user
      - name: epics_28_days_user
      - name: issues_28_days_user
      - name: ci_internal_pipelines_all_time_event
      - name: ci_external_pipelines_all_time_event
      - name: merge_requests_all_time_event
      - name: todos_all_time_event
      - name: epics_all_time_event
      - name: issues_all_time_event
      - name: projects_all_time_event
      - name: deployments_28_days_event
      - name: packages_28_days_event
      - name: sast_jobs_all_time_event
      - name: dast_jobs_all_time_event
      - name: dependency_scanning_jobs_all_time_event
      - name: user_license_management_jobs_all_time_event
      - name: secret_detection_jobs_all_time_event
      - name: container_scanning_jobs_all_time_event
      - name: projects_jenkins_active_all_time_event
      - name: projects_bamboo_active_all_time_event
      - name: projects_jira_active_all_time_event
      - name: projects_drone_ci_active_all_time_event
      - name: jira_imports_28_days_event
      - name: projects_github_active_all_time_event
      - name: projects_jira_server_active_all_time_event
      - name: projects_jira_dvcs_cloud_active_all_time_event
      - name: projects_with_repositories_enabled_all_time_event
      - name: protected_branches_all_time_event
      - name: remote_mirrors_all_time_event
      - name: projects_enforcing_code_owner_approval_28_days_user
      - name: project_clusters_enabled_28_days_user
      - name: analytics_total_unique_counts_monthly
      - name: issues_edit_total_unique_counts_monthly
      - name: user_packages_total_unique_counts_monthly
      - name: terraform_state_api_unique_users_monthly
      - name: incident_management_total_unique_counts_monthly

  - name: prep_gainsight_source_model_counts
    description: '{{ doc("prep_gainsight_source_model_counts") }}'
    columns:
      - name: model_name
        description: Name of the Model 
      - name: row_count 
        description: Number of records in the table