WITH source AS (

    SELECT *
    FROM {{ source('zuora', 'order_action') }}

), renamed AS (

    SELECT
      --Primary Keys
      id::VARCHAR                       AS order_action_id,

      --Info
      accountid AS account_id,
      autogenerated AS auto_generated,
      autorenew AS auto_renew,
      billtocontactid AS bill_to_contact_id,
      cancellationeffectivedate AS cancellation_effective_date,
      changereason AS change_reason,
      clearingexistingbilltocontact AS clearing_existing_bill_to_contact,
      clearingexistingpaymentterm AS clearing_existing_payment_term,
      contracteffectivedate AS contract_effective_date,
      createdbyid AS created_by_id,
      createddate AS created_date,
      currentterm AS current_term,
      currenttermperiodtype AS current_term_period_type,
      customeracceptancedate AS customer_acceptance_date,
      defaultpaymentmethodid AS default_payment_method_id,
      effectivepolicy AS effective_policy,
      orderactionbilltoid AS order_action_bill_to_id,
      orderid AS order_id,
      parentaccountid AS parent_account_id,
      paymentterm AS payment_term,
      renewalterm AS renewal_term,
      renewaltermperiodtype AS renewal_term_period_type,
      renewsetting AS renewal_setting,
      resumedate AS resume_date,
      sequence,
      serviceactivationdate AS service_activiation_date,
      soldtocontactid AS sold_to_contact_id,
      subscriptionid AS subscription_id,
      SubscriptionOwnerAccountBillToId AS subscription_owner_account_bill_to_id,
      SubscriptionOwnerAccountId AS subscription_owner_account_id,
      SubscriptionOwnerAccountSoldToId AS subscription_owner_account_sold_to_id,
      SubscriptionVersionAmendmentId AS amendment_id,
      subtype,
      suspenddate AS suspend_date,
      termstartdate AS term_start_date,
      termtype AS term_type,
      updatedbyid AS updated_by_id,
      updateddate AS updated_date

    FROM source

)

SELECT *
FROM renamed